name: Deploy to Prod

on:
  release:
    types:
      - released

concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Prod
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets: inherit
